# Aliases to move around
alias dsrc="cd /home/michael/dev/dune"

# Git aliases
alias gd="git diff"
alias gs="git status"

# Grep aliases
alias cfind='grep -R -i "$@" --color'                          # Search something in files
alias ffind='find . | grep "$@" --color'                       # Search for file names
alias srcfind='grep "$@" -rni --color --include={*.hpp,*.cpp}' # Search specifically in C++ files

# Mounting and unmounting the NAS
alias mnas-evo="~/tools/dev-tools/scripts/mount_nas.sh 10.10.0.3 /mnt/nas-evo 'home data'"
alias unas-evo="~/tools/dev-tools/scripts/mount_nas.sh 10.10.0.3 /mnt/nas-evo 'home data' true"
alias mnas-home="~/tools/dev-tools/scripts/mount_nas.sh 192.168.0.122 /mnt/nas-home 'shared'"
alias unas-home="~/tools/dev-tools/scripts/mount_nas.sh 192.168.0.122 /mnt/nas-home 'shared' true"

# Facilitate removing RSA key
alias rmkey='ssh-keygen -f "/home/michael/.ssh/known_hosts" -R "$@"'

# Generate/Update CSCOPE database
alias csc="~/tools/cscope-build/cscope_build_db /home/michael/dev/dune/ /home/michael/tools/cscope-build"
